create table if not exists public.drill_progress (
  user_id uuid not null references auth.users (id) on delete cascade,
  drill_uid text not null,
  drill_version integer,
  answers jsonb not null default '{}'::jsonb,
  completed boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default timezone('utc'::text, now()),
  created_at timestamptz not null default timezone('utc'::text, now()),
  primary key (user_id, drill_uid)
);

create table if not exists public.drill_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  attempt_id text not null,
  drill_uid text not null,
  drill_version integer,
  answers jsonb not null default '{}'::jsonb,
  results jsonb not null default '[]'::jsonb,
  summary jsonb,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now()),
  unique (user_id, attempt_id)
);

alter table public.drill_progress enable row level security;
alter table public.drill_attempts enable row level security;

drop policy if exists "Users can read own drill_progress" on public.drill_progress;
create policy "Users can read own drill_progress"
  on public.drill_progress
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own drill_progress" on public.drill_progress;
create policy "Users can insert own drill_progress"
  on public.drill_progress
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own drill_progress" on public.drill_progress;
create policy "Users can update own drill_progress"
  on public.drill_progress
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own drill_progress" on public.drill_progress;
create policy "Users can delete own drill_progress"
  on public.drill_progress
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can read own drill_attempts" on public.drill_attempts;
create policy "Users can read own drill_attempts"
  on public.drill_attempts
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own drill_attempts" on public.drill_attempts;
create policy "Users can insert own drill_attempts"
  on public.drill_attempts
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own drill_attempts" on public.drill_attempts;
create policy "Users can update own drill_attempts"
  on public.drill_attempts
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own drill_attempts" on public.drill_attempts;
create policy "Users can delete own drill_attempts"
  on public.drill_attempts
  for delete
  to authenticated
  using (auth.uid() = user_id);


alter table public.drill_attempts
  add column if not exists last_export_batch_id text,
  add column if not exists last_exported_at timestamptz;
